### ISSUE TITLE
Plan técnico

### ISSUE THREAD

**Issue by enrique-ramirez** [softcraft/inspira.ac#1]
¡Aló!

He estado trabajando en un plan técnico para poder dar una estimación adecuada y hay un par de secciones donde tengo dudas:
## Home
- ¿Los videos estarán hospedados localmente o serán videos en youtube? 
- ¿Qué tanto de las secciones del home quieren que sea editables desde el panel de control? Veo 8 secciones en total y no sé si alguna es "estática" en el sentido de que vivirá en el template o si todas serán "dinámicas" y cualquier admin puede editar el contenido desde el panel de control. Lo que he asumido es:
  - Primera sección (imagen con texto en overlay a la derecha): **No editable**
  - Segunda sección ("Creación de una nueva cultura"): **Editable como una página estática**
  - Tercera (Nuestra cultura): **No editable**
  - Cuarta ("Amplía tu perspectiva de vida"): **No editable**
  - Quinta ("Tú presencia en inspira..."): **Editable como custom posts**
  - Sexta ("Logros"): **Editable como custom posts**
  - Séptima ("Facebook): \* Leer nota
  - Octava ("Un mundo mejor..."): **No editable**
- **Nota**: Esta sección ¿cómo se piensa que va a funcionar? He viste alguno plugins como [este](https://wordpress.org/plugins/facebook-photo-fetcher/) que básicamente agarra las fotos de FB, pero no sé si vaya a ser dinámico o estático. La mayor preocupación es que alguien suba imágenes a FB que no se vean bien en el sitio, sea por el tamaño, el contenido o lo que sea. También quisiera saber si se piensa que acda imagen sea una liga a FB o no.
## Dona

Esta es, quizá, lo sección que más me preocupa por la sección de pago. Hay varias alternativas. La primera es usar un formulario como el que se tiene y manejar la transacción en el backend. Para esto, necesitaríamos varias cosas:
- El sitio tiene que estar en https (o al menos esta sección, pero recomiendo que todo el sitio lo esté, digo, ya teniendo el certificado no hay por qué no).
- Necesitamos saber cómo manejar la transacción. Hay bancos como [Banamex que tienen una maneja que habría que ver cómo implementar](http://www.banamex.com/clickypaga/), pero esto requiere trabajo y esfuerzo extra de desarrollo.

Otra opción es usar un plugin con un servicio que se encargue del manejo del dinero por nosotros. Este método me parece más viable porque:
a) No tenemos que preocuparnos por el manejo de la información de las tarjetas.
b) No tenemos que preocuparnos por la implementación de las mismas, ya la transacción está hecha por nosotros.
c) Es, quizá, el método más rápido de todos.

Sin embargo, el diseño de la página cambiaría muchísimo. El plugin que se ve más accesible es [WP Easy Paypal](https://wordpress.org/plugins/wordpress-easy-paypal-payment-or-donation-accept-plugin/). Puedo medio adaptarlo, pero estoy casi seguro que PayPal tiene guidelines sobre cómo deben verse estos botones y, si no nos adherimos a ellas, nos pueden bloquear el servicio.

La última opción es dejar los datos para que hagan el depósito en el banco y quitar la funcionalidad de hacerlo en línea. Por obvias razones es la más rápida para el desarrollo, pero la menos accesible.

Cualquiera que sea el camino que tomemos, hay un par de cuestiones que no sé cómo manejar:
- ¿Qué hacer o dónde guardar los datos de los donantes? Hay campos de nombre, dirección, etc. etc. que hay que guardar, pero no sé si se tiene ya algún método para esto o si va a ser de cero. Pregunto porque...
- ... ¿Cómo se va a manejar el recibo de donación? Asumo que mucha gente pedirá un recibo, sea para deducir impuestos o lo que sea. ¿Cómo se maneja esto? ¿Quién se encarga de emitirlos? ¿Se necesita desarrollo de algo aquí?
- Una vez hecha la donación, ¿qué se le muestra al usuario? No hay página de "Gracias por tu donación" ni nada por el estilo.
## Nosotros
- La sección de hasta arriba empieza con un slideshow de voluntarios. Estos ¿qué son? ¿Serán usuarios registrados en el WP o custom posts?
- Misma duda del video: self hosted o youtube/similares.
- Misma duda que en el home: ¿qué secciones serán editables desde el backend y cuales vivirán en el template? Mi idea es que todo a excepción de la Misión (que será el contenido de la página en el backend), los voluntarios (que serán como sea que me digan en la primera duda) y los centros inspira (que en la siguiente pregunta toco) serán **no editables**, pero si esto se piensa diferente, háganmelo saber.
- Los centros inspira ¿cómo se piensan manejar? ¿Custom posts? ¿Categorías? ¿estáticos? Cuando se agreguen nuevos centros inspira ¿qué pasará con el mapa? ¿El mapa es dinámico? ¿No sería mejor usar un google map en lugar de lo que se tiene en el PSD?
## Participa
- Las actividades las tengo pensadas como custom posts que pueden estar bajo ciertas categorías. Esto significa que no aparecerán en el Blog, pero sí en esta sección. ¿Esto está bien? 
- Pienso manejar los filtros de "Ciudad" y "Tipo" como categorías padre que tienen categorías hijo (las opciones del dropdown), pero necesito saber la respuesta a la primer pregunta para saber bien cómo manejar esto.
- ¿Qué pasa cuando le pican a "participar"?
- Red de inspiración. Recuerdo me comentaron que esto era un plugin que habían visto. ¿Cuál es?
- Los Beneficios ¿serán editables desde backend o estáticos en el template?
## Qué hacemos
- Misma pregunta que las actividades para los logros. Los tengo pensados como custom posts, osea, no aparecerán en el blog, y necesito saber si esto está bien.
- Estoy asumiendo que los filtros son excluyentes, sólo saber si está bien.
- Hasta abajo hay dos links: "Logros anteriores" y "logros recientes". ¿Esto es una paginación o está pensado para mostrar TODOS los "logros anteriores" que han habido? ¿Esto estará paginado? ¿Qué significa "logro reciente"? ¿Cuál es el tiempo de gracia?
- Los links de las actividades ¿a dónde van? Mi primer instinto es "a la sección de "Participa", pero esta sección no tiene los filtros que aquí se muestran. Existe "tipos" que, supongo, serán "cursos", "eventos" y "voluntariado". ¿He de asumir que debería mandarlos a "Participa" con el tipo seleccionado y ciudad "TODAS"?
- ¿La frase de hasta el final es fija o habrán varias que se irán rotando?
## Generales
- ¿Cómo se piensa manejar las suscripciones? ¿A dónde los voy a suscribir? Es decir, será una mailing list manejada desde WP o se mandaran a algún servicio como mailchimp para procesarlas? ¿qué pasa cuando se suscriben? Es decir, ¿qué les muestro?
- ¿No habrá sección de contacto? Asumo que es de las secciones más importantes para cualquier página de organización, pero no hay manera de contactarse en la versión actual.

Creo que son todas. Cualquier duda, let me know.

**Comment by solojavier** [comment]
Aqui las respuestas:

## Home
- ¿Los videos estarán hospedados localmente o serán videos en youtube? 
  YOUTUBE
- Secciones editables
  - Primera sección (imagen con texto en overlay a la derecha): **No editable**
  - Segunda sección ("Creación de una nueva cultura"): **Editable como una página estática**
  - Tercera (Nuestra cultura): **No editable**
  - Cuarta ("Amplía tu perspectiva de vida"): **No editable**
  - Quinta ("Tú presencia en inspira..."): **Editable como custom posts** (http://deliveringhappiness.com/)
  - Sexta ("Logros"): **Editable como custom posts**
  - Séptima ("Facebook): \* Leer nota
  - Octava ("Un mundo mejor..."): **No editable**
- **Nota**: OK Como yo lo veo funcionando es asi.... que se creen custom posts o algo asi donde definas la imagen y el link cuando des click a ella ... de esta manera se pueden controlar el contenido y cuando le den click, pues te abre el post de la imagen en facebook, aqui lo puedes ver en accion: http://deliveringhappiness.com/community/

## Dona

PODEMOS dejar fuera del scope de este proyecto lo del pago .... por ahora, dejar fuera la ultima seccion donde se introduce la tarjeta y simplemente poner el boton "QUIERO DONAR" y nos manda un email con los datos de la persona que quiere donar y ya la buscamos.... :)
- ¿Qué hacer o dónde guardar los datos de los donantes? Hay campos de nombre, dirección, etc. etc. que hay que guardar, pero no sé si se tiene ya algún método para esto o si va a ser de cero. Pregunto porque...
  se mandan por mail, lo podemos hacer mano.
- ... ¿Cómo se va a manejar el recibo de donación? Asumo que mucha gente pedirá un recibo, sea para deducir impuestos o lo que sea. ¿Cómo se maneja esto? ¿Quién se encarga de emitirlos? ¿Se necesita desarrollo de algo aquí?
  Los contactamos y ya les damos los detalles, en general no damos recibos para donaciones pequeñas pero si los podemos dar, queda fuera esto por ahora.
- Una vez hecha la donación, ¿qué se le muestra al usuario? No hay página de "Gracias por tu donación" ni nada por el estilo.
  Una alerta con un mensaje que definamos para agradecer y decirle que nos pondremos en contacto.

## Nosotros
- La sección de hasta arriba empieza con un slideshow de voluntarios. Estos ¿qué son? ¿Serán usuarios registrados en el WP o custom posts?
  CUSTOM POSTS
- Misma duda del video: self hosted o youtube/similares.
  YOUTUBE, la idea era algo asi: http://digital-deadly-sins.theguardian.com/#/Grid, pero dime si es viable o no....
- Misma duda que en el home: ¿qué secciones serán editables desde el backend y cuales vivirán en el template? Mi idea es que todo a excepción de la Misión (que será el contenido de la página en el backend), los voluntarios (que serán como sea que me digan en la primera duda) y los centros inspira (que en la siguiente pregunta toco) serán **no editables**, pero si esto se piensa diferente, háganmelo saber.
  SI ESTA BIEN
- Los centros inspira ¿cómo se piensan manejar? ¿Custom posts? ¿Categorías? ¿estáticos? Cuando se agreguen nuevos centros inspira ¿qué pasará con el mapa? ¿El mapa es dinámico? ¿No sería mejor usar un google map en lugar de lo que se tiene en el PSD?
  Google maps puede funcionar... pero.... se puede poner con un ZOOM especifico?? ... se pueden editar los colores del google map?

## Participa
- Las actividades las tengo pensadas como custom posts que pueden estar bajo ciertas categorías. Esto significa que no aparecerán en el Blog, pero sí en esta sección. ¿Esto está bien? 
  SI 
- Pienso manejar los filtros de "Ciudad" y "Tipo" como categorías padre que tienen categorías hijo (las opciones del dropdown), pero necesito saber la respuesta a la primer pregunta para saber bien cómo manejar esto.
  SI
- ¿Qué pasa cuando le pican a "participar"?
  CREO QUE PARA ESTO Y LA DE JOVENES seria integrarlo con eventbrite o algo asi... supon por ahora que es un link externo....
- Red de inspiración. Recuerdo me comentaron que esto era un plugin que habían visto. ¿Cuál es?
  este, pero no se si vaya a estar muy caro: http://www.postano.com/products/social-hubs/
- Los Beneficios ¿serán editables desde backend o estáticos en el template?
  Estaticos esta bien...

## Qué hacemos
- Misma pregunta que las actividades para los logros. Los tengo pensados como custom posts, osea, no aparecerán en el blog, y necesito saber si esto está bien.
  SI
- Estoy asumiendo que los filtros son excluyentes, sólo saber si está bien.
  LA idea es que se puedan mezclar varios filtros a la vez, es mucho problema?
- Hasta abajo hay dos links: "Logros anteriores" y "logros recientes". ¿Esto es una paginación o está pensado para mostrar TODOS los "logros anteriores" que han habido? ¿Esto estará paginado? ¿Qué significa "logro reciente"? ¿Cuál es el tiempo de gracia?

Es una paginacion de 8 en 8....
- Los links de las actividades ¿a dónde van? Mi primer instinto es "a la sección de "Participa", pero esta sección no tiene los filtros que aquí se muestran. Existe "tipos" que, supongo, serán "cursos", "eventos" y "voluntariado". ¿He de asumir que debería mandarlos a "Participa" con el tipo seleccionado y ciudad "TODAS"?

SI :)
- ¿La frase de hasta el final es fija o habrán varias que se irán rotando?

ES UNA

## Generales
- ¿Cómo se piensa manejar las suscripciones? ¿A dónde los voy a suscribir? Es decir, será una mailing list manejada desde WP o se mandaran a algún servicio como mailchimp para procesarlas? ¿qué pasa cuando se suscriben? Es decir, ¿qué les muestro?
  Mailchimp
- ¿No habrá sección de contacto? Asumo que es de las secciones más importantes para cualquier página de organización, pero no hay manera de contactarse en la versión actual.

What??? jaja puede ser poner los datos de contacto en el footer ... voy a decirles a los diseñadores que nos manden una propuesta de esos datos de contacto....

Cualquier duda, let me know.
