### ISSUE TITLE
Filtros de todos lados

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#10]

**Comment by enrique-ramirez** [comment]
Según yo, sólo hay dos lugares con filtros:
- En la página de Conoce, la sección de logros.
- En la página de Participa, la sección de actividades.

En Actividades, sólo van a ser filtrables por ciudad ¿cierto? Mientras que los logros por año y ciudad, hasta donde tengo entendido.

**Comment by enrique-ramirez** [comment]
Done as mentioned above. Si hay cambios, let me know. :)
