### ISSUE TITLE
Hacer el sitio responsivo OMG!

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#11]
- [x] Hueco en el carrousel del home
- [x] Cuadrito del home
- [x] Frases no centradas en home (webkit)
- [x]  Hueco a la derecha (iphone)
- [x] Seccion de Participa no sale bien en iphone: 
- [x] ![photo](https://cloud.githubusercontent.com/assets/1088010/13749559/a9f46496-e9c7-11e5-88d6-374624e898a9.jpg)

![img_5848](https://cloud.githubusercontent.com/assets/1088010/12374890/c251ef60-bc70-11e5-9ab8-9b2bdc0cc7f6.PNG)

**Comment by enrique-ramirez** [comment]
¡Ahí voy! Hay demasiados detalles everywhere... :(

**Comment by solojavier** [comment]
Excelente! Tu puedes... jaja

**Comment by solojavier** [comment]
Como vas? @enrique-ramirez

**Comment by enrique-ramirez** [comment]
Ahí voy. Hay partes que hacen dagas, pero ya casi.

**Comment by solojavier** [comment]
Como vamos?

**Comment by enrique-ramirez** [comment]
Should be done by now.
