### ISSUE TITLE
Menu de abajo debe cambiar con las secciones que no son la actual

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#12]
Home: Descubre, conoce, participa, contribuye
Descubre: Descubre, conoce, participa, inspirate
Conce: Descubre, participa, contribuye, inspirate
Participa: Descubre, conoce, contribuye, inspirate

**Comment by enrique-ramirez** [comment]
Necesito saber cómo se ve/qué dice/a dónde va el menú de "Descubre". No está en ninguno de los PSDs.

**Comment by solojavier** [comment]
Descubre == Quienes somos ... ?

**Comment by enrique-ramirez** [comment]
¿Y la imágen? ¿Y el iconito? 
<img width="999" alt="screen shot 2015-09-27 at 11 08 21 am" src="https://cloud.githubusercontent.com/assets/1190640/10123787/16426606-6508-11e5-8bd2-5379b6965fed.png">

Conoce, por ejemplo, tiene una foto de gente en una conferencia y el ícono de un cuadrado blanco.

**Comment by solojavier** [comment]
La imagen completa y lo de abajo son lo mismo...

**Comment by enrique-ramirez** [comment]
El menú también necesita un :hover que cambia la imagen a gris.

**Comment by solojavier** [comment]
![4](https://cloud.githubusercontent.com/assets/1088010/10711813/3adef8e4-7a4d-11e5-90aa-ce2cf1e589d0.png)
![2](https://cloud.githubusercontent.com/assets/1088010/10711814/3ae1d9f6-7a4d-11e5-94e0-6aef5030411a.png)
![1](https://cloud.githubusercontent.com/assets/1088010/10711815/3ae87e64-7a4d-11e5-9e36-0e9e00c918f9.png)
![3](https://cloud.githubusercontent.com/assets/1088010/10711816/3aed1f1e-7a4d-11e5-9d4c-9212a96a6299.png)

**Comment by enrique-ramirez** [comment]
Necesito los íconos como pngs transparentes o algo (el cuadrado, el triángulo, el círculo y el rombo).

**Comment by solojavier** [comment]
Changos o que efecto le podemos poner de mouse over que no requiera eso... porque no los tengo :(

**Comment by enrique-ramirez** [comment]
El "cambiar" las secciones está siendo muy complicado. A veces se repiten colores, a veces aparecen 5 secciones en lugar de 4 y todo es un desmadre. Voy a hacer el :hover effect y dejar lo de desaparecer mágicamente secciones para el final. La lógica está complicada.

**Comment by solojavier** [comment]
Deja fijas esas 4 secciones y ponle el hover... Para ya darle para adelante!

**Comment by enrique-ramirez** [comment]
Este también ya está. Tampoco sé bien en qué commit, pero ya quedó.
