### ISSUE TITLE
EN logros de :conoce, no cabe "Inspira Jovenes"

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#13]
Y tampoco se ve el año, aunque si esta definido... no se si pase con las otras categorias tmb.
http://grab.by/KsYY

**Comment by enrique-ramirez** [comment]
Este es un problema de diseño. Por ahora, [lo arreglé haciendo la fuente de 10px (con otros ajustes)](https://github.com/softcraft/inspira.ac/commit/87ad57b3c682187da0056d79dd92c7bf394c2c2f), pero NO es una solución de verdad.

Necesitamos una definición donde sí quepa el nombre del proyecto ("Inspira Jovenes", "Inspira Vida", etc.), el nombre de la ciudad ("Guadalajara", "México", etc.) y el año. La mejor manera es cambiar esto a que de alguna manera esté vertical y no horizontal. Como alternativa, quitar esta información de aquí y dejar sólo el proyecto o la ciudad. El resto de la información podemos ponerla en el roll-over o algo.

**Comment by solojavier** [comment]
Creoq ue esta bien asi por ahora... a las ciudades les podemos a lo mejor poner una abreviacion?

GDL, CMX, AGS etc... no?

**Comment by enrique-ramirez** [comment]
Ok, lo agrego como un campo extra.

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/ea29c80e3455ed71ce41eb4014ff5bd0dd0ff681
