### ISSUE TITLE
Logros inspiradores en conoce no esta centrado

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#14]
http://grab.by/Kt54

**Comment by enrique-ramirez** [comment]
Lo que no estaba centrado eran los logros en sí, no el texto. Arreglado aquí: https://github.com/softcraft/inspira.ac/commit/18942328ed43b5ab2499c73c98408ad26fb39888

Se tuvo que reducir 15 pixeles el tamaño de cada cuadro (logro) para arreglar esto.
