### ISSUE TITLE
Agregar links de curso eventos y voluntariado en conoce

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#15]

**Comment by enrique-ramirez** [comment]
@solojavier ¿A dónde van estos links? Por el momento, los moví a:
- Cursos: Va a participa, en la sección de eventos.
- Eventos: Igual que Cursos
- Voluntariado: Va a la página de Contribuye.

¿Está bien esto?

**Comment by solojavier** [comment]
Si esta bien :)

**Comment by enrique-ramirez** [comment]
¿Ya puedo cerrar este?
