### ISSUE TITLE
Agregar carrousel de videos en conoce

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#17]

**Comment by solojavier** [comment]
https://www.youtube.com/channel/UCukEfXiCV9m4iwPz56Ns9lg

**Comment by enrique-ramirez** [comment]
Duda: ¿Quieres que jale los videos automáticamente del canal o quieres agregarlos uno por uno? Si es automáticamente del canal, ¿bajo qué criterio? Por ejemplo: los últimos 10 videos.

**Comment by solojavier** [comment]
Del canal esta bien... pero seria genial si se puede escoger el canal dinamicamente y si 10 por ahora suena bien... los ultimos 10.

**Comment by enrique-ramirez** [comment]
Necesitamos un youtube API key: https://developers.google.com/youtube/v3/getting-started

**Comment by solojavier** [comment]
Mejor el que me pusiste por facebook :)

**Comment by enrique-ramirez** [comment]
Este ya está. No sé bien en qué commit, pero ya está.
