### ISSUE TITLE
Información que necesito:

### ISSUE THREAD

**Issue by enrique-ramirez** [softcraft/inspira.ac#2]
Hola @solojavier !

Hice este issue para ir actualizando con las cosas que me van haciendo falta. Por favor, marca como completas cuando las vayas teniendo y pon en negritas o  algo el recurso. :)
## Servidor

Estaría padre ir teniendo el servidor para ir viendo los cambios en vivo. También recuerda que no pudimos migrar la base de datos la vez pasada, así que no tiene caso que me ponga a meter contenido en mi local si de todas formas tendrás que repetirlo en producción. He hecho lo mejor posible por actualizar el README.md con instrucciones de cómo instalar y hacer todo, pero puede que hayan dudas en algún punto.
- [x] Servidor arriba y funcionando.
- [x] Una manera de que yo pueda hacer deploy (o acceso por FTP).
## Contenido & misc.
- [ ] Los videos del home y de la página de conoce. Habíamos acordado que iban a estar en youtube.
- [x] El acceso a Mailchimp. CREO que tiene que ser pagado, pero no estoy seguro.
- [x] La información de depósito para la parte de Dona, o sólo será un correo diciendo algo así como ¿"Ponte en contacto con nosotros para donar"?
- ## Dudas
- [x] En la sección de "conoce" (el PSD se llama "Qué hacemos"), la parte de hasta arriba con las bolitas y el texto... ¿son links? ¿es puro texto? ¿necesitan que sea editable?

Iré actualizando conforme vaya avanzando. Es muy probable que no pueda trabajar en el sitio hasta el fin de semana, pero el fin te mantengo actualizado. Si sale algo muy urgente, por aquí creo que es el mejor medio para comunicarlo.

Aprovecho el ticket para informar que las secciones completas ahorita son: Home, blog index, blog single, conoce. Con sus respectivos detalles: ninguno tiene diseño móvil, esto lo estoy dejando al último (me interesa más que el sitio esté y al no tener una guía visual va a ser prueba y error, tomará tiempo); el home necesita contenido, pero ya está funcionando, al blog le hace falta el filtro de categorías porque aún no sé qué categorías se van a incluir y cuales se van a excluir, el blog single, la parte de comentarios la hice diferente a la del PSD porque, sinceramente, se veía espantoso, pero si hay problema puedo hacer que se vea tal cual el PSD, conoce le faltan unos cuantos estilos, pero ya está funcionando.

¡Saludos!

**Comment by solojavier** [comment]
Link para twitter: https://twitter.com/inspira_ac

**Comment by solojavier** [comment]
```
 En la sección de "conoce" (el PSD se llama "Qué hacemos"), la parte de hasta arriba con las bolitas y el texto... ¿son links? ¿es puro texto? ¿necesitan que sea editable?
```

Al dar click en ellos, aparece del lado derecho la informacion y los demas se ponen en color bajito.....

Los proyectos e iconos es poco probable que cambien... la descripcion si estaria bien que fuera editable.

**Comment by solojavier** [comment]
```
La información de depósito para la parte de Dona, o sólo será un correo diciendo algo así como ¿"Ponte en contacto con nosotros para donar"?
```

Mas bien seria que nos manden sus datos y algo como: "Gracias por tu interés, un representante de Inspira se pondrá en contacto contigo a la brevedad.

**Comment by solojavier** [comment]
@enrique-ramirez El acceso ftp segun yo con la misma cuenta que te cree para la de jovenes deberias poder ver esta misma... pero sino me dices y te doy acceso...

Ya esta en linea el servidor tmb: http://inspira.ac ... voy a estar trabajando en agregar la info y configuracion en estos dias.

**Comment by enrique-ramirez** [comment]
@solojavier estoy un poco confundido con la parte de "Centros Inspira" en la sección de Descubre. 
- ¿Le van a dar click en el mapa para mostrar los centros en su ciudad? Si sí, la mejor opción es comprar un mapa (como este: http://winstonwolf.pl/clickable-maps/mexico.html ).
- ¿Cómo quieres manejar esto? Hay dos opciones, creo, porque están agrupados por estado:
1. Crear un custom post con una taxonomía custom (como los Logros con su "Año" y "Proyecto").
2. Que sean una taxonomía en sí. Lo pienso como categorías padre ("Jalisco") con categorías hijo ("Minerva").

La ventaja de la segunda es que puedes aplicar "Minerva" a un blog post, a un logro, etc. mientras que la primer opción es algo que vive aparte de todo. La desventaja es que tendrían que crearlas primero para yo poder hacerlas (porque dependo de los IDs) y editarlas/agregarlas/etc. es bien pinches complicado.

**Comment by solojavier** [comment]
@enrique-ramirez Los centros en teoria funciona como sigue... hay un globito morado por cada "ciudad" y cuando le dan click ahi aparecen abajo los centros que hay en esa ciudad, si dan click en un centro, se abre un lightbox con los datos del centro y fotos y asi... ahi en el PSD viene.

Cual crees que sea la mejor opcion? Me gusta que se puedan usar las mismas "categorias" en todos lados.....

**Comment by enrique-ramirez** [comment]
Ok, la funcionalidad está complicada pero sí se puede. Los hacemos categorías, donde el padre" sería "Jalisco" y las categorías hijo serían "Minerva" y así.

Va a tomar un poco de tiempo, pero si puedes irme ayudando con esto estaría de lujo:
1. Crearme una cuenta en el servidor con acceso de admin.
2. Hacerme una lista con los datos de los centros. Hasta donde veo, los datos son:
a) Estado
b) Nombre
c) Teléfono
d) Dirección
e) Mapa de google maps (la URL)
f) Galería de imágenes.

En cuanto tengas eso, avísame por aquí y yo hago el resto.

Para el mapa, si encuentras una solución gratuita me avisas (lo único que necesito realmente es que pueda bindear eventos de JavaScript al hacer click en los estados). Si no, creo que ese que puse arriba cumple con los requisitos y hay que comprarlo. :)

**Comment by solojavier** [comment]
Hola Enrique, estoy un poco perdido con la info que tengo que dar de alta para que funcione la pagina, tengo dos ideas:
1. Ya te di acceso de admin al WP de Inspira... si tu puedes ir avanzando en eso para poder mostrar el avance el fin de semana, estaria de perlas.
2. Nos reunimos la proxima semana para darle juntos hasta que salga y tengamos ambos toda la info que se necesite....

Quedo al pendiente.

**Comment by solojavier** [comment]
Aqui esta lo de los videos @enrique-ramirez :+1: 
https://www.youtube.com/channel/UCukEfXiCV9m4iwPz56Ns9lg
