### ISSUE TITLE
Logo sale muy grande y desfasado, se puede ajustar? o que medidas debe tener?

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#20]
http://grab.by/KGHy

**Comment by enrique-ramirez** [comment]
No hay una medida fija, porque no sé cómo sean los logos, qué aspect ratio tienen o qué tanto espacio vertical ocupan.

Horizontalmente, no deberían pasar de 380px.

**Comment by enrique-ramirez** [comment]
Actually, nvm. Arreglado aquí: https://github.com/softcraft/inspira.ac/commit/f85a89a26a7e12be1ca0ce561f8099cb70a612b7

Pero necesitas subir los logos de nuevo.

**Comment by solojavier** [comment]
Okay :)
