### ISSUE TITLE
Mejorar performance

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#26]
Vi esta reporte y creo que se podrian atender varias cosas que no se ven tan dificiles de hacer?

https://gtmetrix.com/reports/inspira.ac/xiDB5tBY

Crees que se pueda???

**Comment by enrique-ramirez** [comment]
Veo estos puntos en rojo:
- Defer parsing of JavaScript - Este es bastante complicado y brinda muy poco cambio (a menos que estés en windows xp con IE7 o algo así). El parsear el JS es bastante rápido y hacer lo que sugiere requiere de hacks y trickeries que WP no está diseñado para hacer.
- Leverage browser caching - Esto es de servidor. Hay un par de plugins que probablemente puedan ayudar, voy a investigar.
- Specify image dimensions - Las imágenes carecen de dimensiones por la decisión de diseño y que sea responsivo.  Igual, un repaint en un navegador es suficientemente rápido como para ser imperceptible. No vale la pena.
- Enable gzip compression - Otra cosa de servidor. También creo que hay un plugin para esto.

El resto están en verde y una en amarillo (minificar el CSS). 

La mayoría de los problemas de performance vienen del servidor, no del frontend though. Si bien podemos hacer un par de estos puntos, no verás un cambio drástico en performance (a excepción, quizá, de gzip).

**Comment by solojavier** [comment]
Hagamos lo del gzip y veamos si funciona :)

O dime como hacerle y le muevo...

**Comment by solojavier** [comment]
Hola @enrique-ramirez, ya estuve haciendo varios cambios y ya me da un score bastante bueno, pero...

http://inspira.ac/wp-admin/options-general.php?page=sbp-options

^^ Si habilito las opciones de "defer javascript" y "move to footer", el mapa de descubre deja de funcionar... hay manera de que podamos hacer funcionar el mapa con esas opciones?

**Comment by solojavier** [comment]
Le agregue fastly y parece que jala perron, pero .... ahora el primer request es el que tarda... me dicen que puede ser por la db? Tu que crees que se pueda hacer?

**Comment by solojavier** [comment]
http://grab.by/OCcw

**Comment by solojavier** [comment]
segun esta cosa: https://developers.google.com/speed/pagespeed/insights/?url=inspira.ac&tab=desktop ... el blocking javascript y eso es lo único que estaría pendiente.

**Comment by solojavier** [comment]
Ya esta bastante decente , asi que olvidalo por ahora :)

**Comment by enrique-ramirez** [comment]
Ok. Si aún quieres mejorarlo un poco, estuve checando unos plugins para minificar los assets, y este parece bueno: https://es-mx.wordpress.org/plugins/bwp-minify/

Me dio un poco de miedo probarlo en producción, though. Creo que sería bueno tener una copia de seguridad antes de jugar con él.
