### ISSUE TITLE
En conoce que hacemos, por default pondria DA CLICK EN LOS CIRCULOS PARA CONOCER NUESTROS PROYECTOS...

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#37]
porque ahorita sale por default INSPIRA VIDA y puedes dar scroll y ni te enteras de nada.

**Comment by enrique-ramirez** [comment]
¿En qué parte? ¿Como encabezado?

**Comment by solojavier** [comment]
Puede ser como encabezado, pero el chiste es que salga en blanco por default, en lugar de salir Inspira vida...

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/b93c193ff009cda21734cc5097594f2a500500ed
