### ISSUE TITLE
Hacer fotos de voluntarios en Descubre más grandes

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#40]
Como se quitó el video, pues ya queda más espacio...

Algo así:

![unnamed](https://cloud.githubusercontent.com/assets/1088010/13660294/68c11586-e64e-11e5-9b43-536adaf49148.png)

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/1478b21a6117fb14192752b37a5bd74336b32427
