### ISSUE TITLE
Link no funciona en iconos de como colaborar en home

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#44]
En donde editas las acciones, "participa", "dona", "difunde", "inspira" viene un campo que dice "link", pero el código no usa ese valor para hacer el link, sino que le agrega el titulo.. 

Entonces al dar click en inspira trata de abrir "inspira.ac/inspira" o para "inspira.ac/difunde" lo cual no es correcto :(

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/f4167f89214ccfd9f9c12d30a4419631dffe3b3b
