### ISSUE TITLE
Detalles con logros inspiradores en descubre

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#45]
- [x] Hacer más grande dropdown de proyectos (Padres y Maestros no cabe)
- [x] El año y la ciudad no se ven en padres y maestros (Se puede que se ponga en dos lineas para que salga completo el nombre?, sino al menos que si salga el año y la ciudad aunque se corte)
- [ ] Alinear los cuadros cuando hay menos de 4 por línea a la izquierda (porque por ejemplo si hay 7 en una página, se ven como desalineados)

<img width="392" alt="screen shot 2016-03-16 at 8 33 34 p m" src="https://cloud.githubusercontent.com/assets/1088010/13834720/d9f3e0ae-ebb6-11e5-8487-f0b7895d85d3.png">
<img width="624" alt="screen shot 2016-03-16 at 8 33 50 p m" src="https://cloud.githubusercontent.com/assets/1088010/13834721/d9f4fb4c-ebb6-11e5-9ea2-d14c66038313.png">
<img width="867" alt="screen shot 2016-03-16 at 8 34 29 p m" src="https://cloud.githubusercontent.com/assets/1088010/13834722/da046492-ebb6-11e5-8717-09525095b956.png">

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/bfe28afac00e721e311aa8e8ffef9ca5939270c2

El último punto (alinear a la izquierda) tiene dagas:
1. No puedo alinear condicionalmente (de que, "si son 2, alinea a la izquierda, pero si son 4, centralos). Si alineo a la izquierda, alineo siempre.
2. Como el diseño está pensado para ser fluído (en dimensiones), se ve sumamente extraño tener las cosas alineadas a la izquierda. Adjunto dos screens.

<img width="709" alt="screen shot 2016-03-18 at 11 17 42 am" src="https://cloud.githubusercontent.com/assets/1190640/13886125/1338ac10-ecfb-11e5-9b06-3926de194c72.png">
<img width="1054" alt="screen shot 2016-03-18 at 11 17 29 am" src="https://cloud.githubusercontent.com/assets/1190640/13886126/13396be6-ecfb-11e5-9034-9c211a962d06.png">

Si quieres, lo alineo a la izquierda, pero no creo que se vea bien.

**Comment by solojavier** [comment]
Ta bien asi :)
