### ISSUE TITLE
Footer no se corta igual que las otras secciones

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#47]
<img width="1275" alt="screen shot 2016-03-16 at 9 34 23 p m" src="https://cloud.githubusercontent.com/assets/1088010/13835652/978065e0-ebbf-11e5-9b66-615c2955bb77.png">

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/927700d0471c8a2ac1f95baf4c14a771cb760038
