### ISSUE TITLE
BUG!!! URGENTE al dar de alta eventos

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#48]
Cuando escoges la fecha en el calendario se escribe asi: "abril 21 2016 12:00 p.m.", pero al dar guardar se borra la fecha, si le cambio manualmente a: "april 21 2016 12:00 p.m." entonces si se guarda. Entonces como que hay que actualizar el idiioma de la fecha o poner otro formato que se yo

**Comment by solojavier** [comment]
También la fecha se muestra con un solo número en la vista del single page del evento: "1461240000". Aquí un ejemplo: http://inspira.ac/eventos/apertura-el-poder-de-ser-tu-mismo/ habría que darle un formato o algo jaja

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/fa06616d3e5b827dbdd72ac66e4898da46eabc22
https://github.com/softcraft/inspira.ac/commit/e190d6332b76eb681dfab9cfd794c835992ee443
