### ISSUE TITLE
BUG - Conoce se descompuso el slider cuando actualicé el plugin

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#49]
Fatal error: Call to undefined function putRevSlider() in /nfs/c05/h04/mnt/160231/domains/inspira.ac/html/wp-content/themes/inspira.ac/conoce.php on line 188

**Comment by solojavier** [comment]
Estaba desactivado. Duh sorry :)

**Comment by enrique-ramirez** [comment]
Jajajajajajajajajaja
