### ISSUE TITLE
Ajustar imagenes de home

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#52]
Para ciertas resoluciones, salen asi: :(

<img width="813" alt="screen shot 2016-04-23 at 10 52 18 a m" src="https://cloud.githubusercontent.com/assets/1088010/14762498/84d7eb1c-0941-11e6-9078-840c68262541.png">

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/f30a9094996a7fe034ed4e2dbc0ab52ccbc29c34
