### ISSUE TITLE
tu apoyo hace la diferencia, encuadrar...

### ISSUE THREAD

**Issue by solojavier** [softcraft/inspira.ac#8]

**Comment by enrique-ramirez** [comment]
¿?

**Comment by solojavier** [comment]
En la pagina de "Descubre : Quienes somos" La parte donde viene esa frase con fondo verde... se expande hacia los lados... y creo que seria mejor encuadrarlo como las demas partes...

**Comment by enrique-ramirez** [comment]
AH, ya entendí. Ok.

**Comment by enrique-ramirez** [comment]
https://github.com/softcraft/inspira.ac/commit/43307f77221047bfe54d70aac8ed9dd41e1bcf2c
